const nav = [
  {
    title: 'Vue介绍',
    path: '/home',
    icon: 'el-icon-menu',
    display: false,
    children: []
  }, {
    title: 'Vue基础',
    path: '/basic',
    icon: 'el-icon-menu',
    display: true,
    children: [{
      title: 'Vue实例',
      path: '/basic/instance',
      display: true,
      children: []
    }, {
      title: '模板语法',
      path: '/basic/template',
      display: true,
      children: []
    }, {
      title: '计算属性',
      path: '/basic/computed',
      display: true,
      children: []
    }, {
      title: '监听器',
      path: '/basic/watch',
      display: true,
      children: []
    }, {
      title: 'class与style',
      path: '/basic/css',
      display: true,
      children: []
    }, {
      title: '条件渲染',
      path: '/basic/if',
      display: true,
      children: []
    }, {
      title: '列表渲染',
      path: '/basic/for',
      display: true,
      children: []
    }, {
      title: '事件处理',
      path: '/basic/event',
      display: true,
      children: []
    }, {
      title: '表单输入绑定',
      path: '/basic/form',
      display: true,
      children: []
    }, {
      title: '组件基础',
      path: '/basic/component',
      display: true,
      children: []
    }]
  }, {
    title: '深入组件',
    path: '/component',
    icon: 'el-icon-menu',
    display: true,
    children: [{
      title: '组件注册',
      path: '/component/subscribe',
      display: true,
      children: []
    }, {
      title: 'Prop',
      path: '/component/prop',
      display: true,
      children: []
    }, {
      title: '自定义事件',
      path: '/component/customEvent',
      display: true,
      children: []
    }, {
      title: '插槽',
      path: '/component/slot',
      display: true,
      children: []
    }, {
      title: '动态组件',
      path: '/component/dynamic',
      display: true,
      children: []
    }]
  }, {
    title: '过渡与动画',
    path: '/animation',
    icon: 'el-icon-menu',
    display: true,
    children: [{
      title: '进入/离开',
      path: '/animation/transition',
      display: true,
      children: []
    }, {
      title: '状态过渡',
      path: '/animation/state',
      display: true,
      children: []
    }]
  }, {
    title: '可复用',
    path: '/repeatable',
    icon: 'el-icon-menu',
    display: true,
    children: [{
      title: '混入',
      path: '/repeatable/mixin',
      display: true,
      children: []
    }, {
      title: '自定义指令',
      path: '/repeatable/directive',
      display: true,
      children: []
    }, {
      title: '渲染函数',
      path: '/repeatable/render',
      display: true,
      children: []
    }, {
      title: '插件',
      path: '/repeatable/plugin',
      display: true,
      children: []
    }, {
      title: '过滤器',
      path: '/repeatable/filter',
      display: true,
      children: []
    }]
  }, {
    title: '规模化',
    path: '/model',
    icon: 'el-icon-menu',
    display: true,
    children: [{
      title: '路由',
      path: '/setting/router',
      display: true,
    }, {
      title: '状态管理',
      path: '/setting/store',
      display: true,
    }]
  }, {
    title: '深入响应式原理',
    path: '/responsive',
    icon: 'el-icon-menu',
    display: true,
    children: []
  }, {
    title: 'Element-UI',
    path: '/element',
    icon: 'el-icon-menu',
    display: true,
    children: [{
      title: '引入Element-UI',
      path: '/element/import',
      icon: 'el-icon-menu',
      display: true,
      children: []
    }, {
      title: 'Layout布局',
      path: '/element/basic/layout',
      display: true,
      children: []
    }, {
      title: 'Container布局容器',
      path: '/element/basic/container',
      display: true,
      children: []
    }, {
      title: 'Color',
      path: '/element/basic/color',
      display: true,
      children: []
    }, {
      title: 'typography字体',
      path: '/element/basic/typography',
      display: true,
      children: []
    }, {
      title: 'Icon图标',
      path: '/element/basic/icon',
      display: true,
      children: []
    }, {
      title: 'Button按钮',
      path: '/element/basic/button',
      display: true,
      children: []
    }]
  }, {
    title: 'form表单',
    path: '/element/form',
    icon: 'el-icon-menu',
    display: true,
    children: [{
      title: 'Radio单选框',
      path: '/element/form/radio',
      display: true,
      children: []
    }, {
      title: 'Checkbox多选框',
      path: '/element/form/checkbox',
      display: true,
      children: []
    }, {
      title: 'Input输入框',
      path: '/element/form/input',
      display: true,
      children: []
    }, {
      title: 'InputNumber数字输入框',
      path: '/element/form/inputNumber',
      display: true,
      children: []
    }, {
      title: 'Select选择框',
      path: '/element/form/select',
      display: true,
      children: []
    }, {
      title: 'Cascader级联选择器',
      path: '/element/form/cascader',
      display: true,
      children: []
    }, {
      title: 'Switch',
      path: '/element/form/switch',
      display: true,
      children: []
    }, {
      title: 'slider滑块',
      path: '/element/form/slider',
      display: true,
      children: []
    }, {
      title: 'timePicker',
      path: '/element/form/timePicker',
      display: true,
      children: []
    }, {
      title: 'datePicker日期选择器',
      path: '/element/form/datePicker',
      display: true,
      children: []
    }, {
      title: 'Upload上传',
      path: '/element/form/upload',
      display: true,
      children: []
    }, {
      title: 'Rate评分',
      path: '/element/form/rate',
      display: true,
      children: []
    }, {
      title: 'ColorPicker颜色选择器',
      path: '/element/form/colorPicker',
      display: true,
      children: []
    }, {
      title: 'Transfer 穿梭框',
      path: '/element/form/transfer',
      display: true,
      children: []
    }, {
      title: '表单',
      path: '/element/form/form',
      display: true,
      children: []
    }]
  }, {
    title: 'Data',
    path: '/element/component',
    display: true,
    icon: 'el-icon-menu',
    children: [{
      title: '表格',
      path: '/element/data/table',
      display: true,
      children: []
    }, {
      title: 'Tag 标签',
      path: '/element/data/tag',
      display: true,
      children: []
    }, {
      title: 'Progress 进度条',
      path: '/element/data/progress',
      display: true,
      children: []
    }, {
      title: 'Tree 树形控件',
      path: '/element/data/tree',
      display: true,
      children: []
    }, {
      title: 'Pagination 分页',
      path: '/element/data/pagination',
      display: true,
      children: []
    }, {
      title: 'Badge 标记',
      path: '/element/data/badge',
      display: true,
      children: []
    }]
  }, {
    title: 'Notice',
    path: '/element/notice',
    display: true,
    icon: 'el-icon-menu',
    children: [{
      title: 'Alert 警告',
      path: '/element/notice/alert',
      display: true,
      children: []
    }, {
      title: 'Loading 加载',
      path: '/element/notice/loading',
      display: true,
      children: []
    }, {
      title: 'Message 消息提示',
      path: '/element/notice/message',
      display: true,
      children: []
    }, {
      title: 'MessageBox 弹框',
      path: '/element/notice/messageBox',
      display: true,
      children: []
    }, {
      title: 'Notification 通知',
      path: '/element/notice/notification',
      display: true,
      children: []
    }]
  }, {
    title: 'Navigation',
    path: '/element/navigation',
    display: true,
    icon: 'el-icon-menu',
    children: [{
      title: 'NavMenu 导航菜单',
      path: '/element/navigation/navMenu',
      display: true,
      children: []
    }, {
      title: 'Tabs 标签页',
      path: '/element/navigation/tabs',
      display: true,
      children: []
    }, {
      title: 'Breadcrumb 面包屑',
      path: '/element/navigation/breadcrumb',
      display: true,
      children: []
    }, {
      title: 'Dropdown 下拉菜单',
      path: '/element/navigation/dropdown',
      display: true,
      children: []
    }, {
      title: 'Steps 步骤条',
      path: '/element/navigation/steps',
      display: true,
      children: []
    }]
  }, {
    title: 'others',
    path: '/element/others',
    display: true,
    icon: 'el-icon-menu',
    children: [{
      title: 'Dialog 对话框',
      path: '/element/others/dialog',
      display: true,
      children: []
    }, {
      title: 'Tooltip 文字提示',
      path: '/element/others/tooltip',
      display: true,
      children: []
    }, {
      title: 'Popover 弹出框',
      path: '/element/others/popover',
      display: true,
      children: []
    }, {
      title: 'Card 卡片',
      path: '/element/others/card',
      display: true,
      children: []
    }, {
      title: 'Carousel 走马灯',
      path: '/element/others/carousel',
      display: true,
      children: []
    }, {
      title: 'Collapse 折叠面板',
      path: '/element/others/collapse',
      display: true,
      children: []
    }]
  }];

export default nav;
